#/bin/bash
SERVER_NAME=localhost
PORT_NUMBER=3306
USER=su01
PASSWORD=uidai123
DATABASE_NAME=uidmasterv1_1
LOG_FILE=statusAPI_messages_log.txt

error_flag=0
if ls $LOG_FILE
then
echo "Log File already existing"
else
echo "New Log File created"
touch $LOG_FILE
fi


mysql -h $SERVER_NAME -P $PORT_NUMBER -u $USER  -p$PASSWORD -e "Use $DATABASE_NAME" 2>> $LOG_FILE;
if [ $? -eq 0 ] && [ $error_flag -eq 0 ]
then
echo "date:Use Statement successful" >> $LOG_FILE
else
echo "date:Use Statement failed" >> $LOG_FILE
error_flag=1
exit
fi
mysql -h $SERVER_NAME -P $PORT_NUMBER -u $USER -p$PASSWORD $DATABASE_NAME  -e "INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(45,	'EID_RES_REJECTED_DUE_TO_DEPENDENT_ENRL_REJECTED',	'This enrolment has been rejected as dependent enrolment is rejected. Please check the status of dependent enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(46,	'EID_RES_REJECTED_DUE TO_GUARDIAN_ENRL_REJECTED',	'This enrolment has been rejected due to rejection of guardian\'s enrolment. Please check the status of guardian\'s enrolment. If guardian Aadhaar is not generated, Kindly re-enrol guardian first & then get yourself re-enrolled under him/her OR use any other method for enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(47,	'EID_RES_REJECTED_DUE_TO_GUARDIAN_BIO_MATCH_FAILED',	'This enrolment has been rejected due to guardian\'s biometric matching failed. Please re-enrol if you do not have Aadhaar from any other enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(48,	'EID_RES_REJECTED_DUE_TO_BIO_MATCH_FAILED',	'This update request has been rejected as your biometric matching failed. Please update again',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(49,	'EID_RES_REJECTED_DUE_TO_BIO_ISSUE',	'This enrolment has been rejected due to biometric issues. Kindly contact UIDAI helpline at 1947 or contact nearest UIDAI Regional office. Contact details available at uidai.gov.in',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(50,	'EID_RES_REJECTED_DUE_TO_HOF_BIO_MATCH_FAILED',	'This enrolment has been rejected due to Head of Family\'s biometric matching failed. Please re-enrol if you do not have Aadhaar from any other enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(51,	'EID_RES_REJECTED_DUE_TO_HOF_ENRL_REJECTED',	'This enrolment has been rejected due to rejection of head of family\'s enrolment. Please check the status of head of family\'s enrolment. If Head of Family Aadhaar is not generated, Kindly re-enrol Head of Family first & then get yourself re-enrolled under him/her OR use any other method for enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(52,	'EID_RES_REJECTED_DUE_TO_GAURDIAN_HOF_AGE_LESSER_THAN_EIGHTEEN',	'This enrolment has been rejected as age of guardian/head of family is less than 18 years. Please re-enrol with your Adult guardian/head of family if you do not have Aadhaar from any other enrolment OR use any other method for enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(53,	'EID_RES_REJECTED_DUE_TO_GAURDIAN_HOF_ENRL_NOT_DOC_BASED',	'This enrolment has been rejected as guardian\'s/head of family\'s enrolment is not document based. Please re-enrol with valid supporting documents',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(54,	'EID_RES_REJECTED_DUE_TO_GUARDIAN_HOF_UID_INVALID',	'This enrolment has been rejected as guardian\'s/head of family\'s Aadhaar Number is invalid. Please re-enrol  under guardian\'s/head of family\'s with valid Aadhaar Number if you do not have Aadhaar from any other enrolment OR use any other method for enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(55,	'EID_RES_REJECTED_DUE_TO_INVALID_POI',	'This enrolment has been rejected due to invalid proof of identity document. Please re-enrol if you do not have Aadhaar from any other enrolment. List of Valid supporting documents is available at UIDAI official website www.uidai.gov.in',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(56,	'EID_RES_REJECTED_DUE_TO_INVALID_POA',	'This enrolment has been rejected due to invalid proof of address document. Please re-enrol with valid document, if you do not have Aadhaar from any other enrolment. List of Valid supporting documents is available at UIDAI official website www.uidai.gov.in',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(57,	'EID_RES_REJECTED_DUE_TO_INVALID_HOF',	'This enrolment has been rejected due to invalid proof of head of family document. Please re-enrol if you do not have Aadhaar from any other enrolment. List of Valid supporting documents is available at UIDAI official website www.uidai.gov.in',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(58,	'EID_RES_REJECTED_DUE_TO_TRANSLITERATION_ERROR',	'This enrolment has been rejected due to local language transliteration error. Please re-enrol if you do not have Aadhaar from any other enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(59,	'EID_RES_REJECTED_DUE_TO_INVALID_GUARDIAN_UID',	'This enrolment has been rejected as guardian\'s Aadhaar number is invalid. Please re-enrol with valid Aadhaar number of guardian, if you do not have Aadhaar from any other enrolment OR use any other method for enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(60,	'EID_RES_REJECTED_DUE_TO_INVALID_DOB',	'This enrolment has been rejected due to invalid date of birth. Please re-enrol if you do not have Aadhaar from any other enrolment',	'System',	'System',	Now(),	Now())				
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(61,	'EID_RES_REJECTED_DUE_TO_OPERATOR_VERIFICATION_FAILED',	'This enrolment has been rejected as operator verification failed. Please re-enrol only from the authorised enrolment centres, if you do not have Aadhaar from any other enrolment. List of such centres are available on UIDAI official website www.uidai.gov.in',	'System',	'System',	Now(),	Now())					
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(62,	'EID_RES_REJECTED_DUE_TO_OPERATOR_SUPERVISOR_VERIFICATION_FAILED',	'This enrolment has been rejected as operator/supervisor verification failed. Please re-enrol only from the authorised enrolment centres, if you do not have Aadhaar from any other enrolment. List of such centres are available on UIDAI official website www.uidai.gov.in',	'System',	'System',	Now(),	Now())					
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(63,	'EID_RES_REJECTED_DUE_TO_INTRODUCER_VERIFICATION_FAILED',	'This enrolment has been rejected as introducer verification failed. Please re-enrol only from the authorised enrolment centres, if you do not have Aadhaar from any other enrolment. List of such centres are available on UIDAI official website www.uidai.gov.in',	'System',	'System',	Now(),	Now())					
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(64,	'EID_RES_REJECTED_DUE_TO_INVALID_POB',	'This enrolment has been rejected due to invalid proof of date of birth document. Please re-enrol if you do not have Aadhaar from any other enrolment. List of Valid supporting documents is available at UIDAI official website www.uidai.gov.in',	'System',	'System',	Now(),	Now())						
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(65,	'EID_RES_REJECTED_DUE_TO_BIO_UPDATE_REQUIRED',	'This update request has been rejected as biometrics update is required for your Aadhaar. Please update biometrics along with demographics',	'System',	'System',	Now(),	Now())			
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(66,	'EID_RES_REJECTED_DUE_TO_OPERATOR_SUPERVISOR_VERIFICATION_FAILED',	'This enrolment has been rejected as operator/supervisor verification failed. Please re-enrol only from the authorised enrolment centres, if you do not have Aadhaar from any other enrolment. List of Valid supporting documents is available at UIDAI official website www.uidai.gov.in',	'System',	'System',	Now(),	Now())						
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(67,	'EID_RES_REJECTED_DUE_TO_GUARDIAN_UID_INVALID',	'This enrolment has been rejected as guardian\'s Aadhaar Number invalid. Please re-enrol if you do not have Aadhaar from any other enrolment',	'System',	'System',	Now(),	Now())						
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(68,	'EID_RES_REJECTED_DUE_TO_BIOMETRIC_UPDATE_NOT_ALLOWED_FOR_CHILDREN',	'This update request has been rejected as fingerprints & IRIS update is not allowed for Children less than 5 years of age. Please update only demographic details',	'System',	'System',	Now(),	Now())			
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(69,	'EID_RES_REJECTED_DUE_TO_GAURDIAN_INVALID',	'This enrolment has been rejected as age of guardian is less than 18 years. Please re-enrol under Adult guardian if you do not have Aadhaar from any other enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(70,	'EID_RES_REJECTED_DUE_TO_UID_MISSING',	'This update request has been rejected as Aadhaar number is missing. Please update again with valid Aadhaar Number.',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(71,	'EID_RES_REJECTED_DUE_TO_GAURDIAN_BIO__VERIFICATION_FAILED',	'This enrolment has been rejected as guardian\'s biometric verification failed. Please re-enrol if you do not have Aadhaar from any other enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(72,	'EID_RES_REJECTED_DUE_TO_INVALID_DOC',	'This enrolment has been rejected as valid documents are not available. Please re-enrol if you do not have Aadhaar from any other enrolment. List of Valid supporting documents is available at UIDAI official website www.uidai.gov.in',	'System',	'System',	Now(),	Now())			
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(73,	'EID_RES_REJECTED_DUE_TO_UID_INVALID',	'This update request has been rejected due to invalid Aadhaar Number. Please update again with valid Aadhaar number',	'System',	'System',	Now(),	Now())					
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(74,	'EID_RES_REJECTED_DUE_TO_UID_INACTIVE',	'This update request has been rejected as your Aadhaar number is inactive. Please update your biometric to activate Aadhaar',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(75,	'EID_RES_REJECTED_DUE_TO_CORRELATION_REQ_LIMIT_EXCEEDED',	'This correction request has been rejected as you have exceeded correction request limit. Please update after Aadhaar generation',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(76,	'EID_RES_REJECTED_DUE_TO_CORRECTION_DONE_AFTER_ALLOWED_TIME_LIMIT',	'This correction request has been rejected as correction done after 96 Hrs correction window. Please update after Aadhaar generation',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(77,	'EID_RES_REJECTED_DUE_TO_ENRL_ID_MISSING',	'This correction request has been rejected due to Enrolment ID is missing. Please update after Aadhaar generation',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(78,	'EID_RES_REJECTED_DUE_TO_GUARDIAN_ENRL_ID_NOT_FOUND',	'This enrolment has been rejected as guardian Enrolment ID was not found. Please re-enrol if you do not have Aadhaar from any other enrolment',	'System',	'System',	Now(),	Now())					
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(79,	'EID_RES_REJECTED_DUE_TO_GUARDIAN_HOF_ENRL_IN_PROCESS',	'This enrolment has been rejected as guardian\'s/head of family\'s enrolment is in process. Please re-enrol if you do not have Aadhaar, after guardian\'s/head of family\'s Aadhaar get generated OR use any other method for enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(80,	'EID_RES_REJECTED_DUE_TO_GUARDIAN_HOF_ENRL_ID_INVALID',	'This enrolment has been rejected as guardian\'s/head of family\'s enrolment ID is invalid. Please re-enrol if you do not have Aadhaar, with valid guardian\'s/head of family\'s enrolment/Aadhaar Number OR use any other method for enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(81,	'EID_RES_REJECTED_DUE_TO_GUARDIAN_ENRL_ID_INVALID',	'This enrolment has been rejected as guardian\'s enrolment ID is invalid. Please re-enrol if you do not have Aadhaar, with valid guardian\'s enrolment/Aadhaar Number OR use any other method for enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(82,	'EID_RES_REJECTED_DUE_TO_GUARDIAN_ENRL_IN_PROCESS',	'This enrolment has been rejected as guardian\'s enrolment is in process. Please re-enrol if you do not have Aadhaar, after guardian\'s enrolment gets processed OR use any other method for enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(83,	'EID_RES_REJECTED_DUE_TO_UID_GENERATED_WITH_OTHER_EID',	'This enrolment has been rejected as your Aadhaar is already generated with other Enrolment ID. Please search for your Aadhaar, through find Aadhaar facility in nearest enrolment centre and do not re-enrol. ',	'System',	'System',	Now(),	Now())						
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(84,	'EID_RES_REJECTED_DUE_TO_GUARDIAN_ENRL_IN_PROCESS',	'This enrolment has been rejected as guardian\'s enrolment is in process. Please re-enrol if you do not have Aadhaar, after guardian\'s Aadhaar gets generated OR use any other method for enrolment',	'System',	'System',	Now(),	Now())					
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(85,	'EID_RES_REJECTED_DUE_TO_BIO_ISSUES',	'This update has been rejected due to biometric issues. Kindly contact UIDAI helpline at 1947 or contact nearest UIDAI Regional office. Contact details available at uidai.gov.in.',	'System',	'System',	Now(),	Now())							
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(86,	'EID_RES_REJECTED_DUE_TO_TECHNICAL_REASON',	'This enrolment has been rejected due to technical reason. Please re-enrol if you do not have Aadhaar from any other enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(87,	'EID_RES_REJECTED_DUE_TO_HOF_VERIFICATION_FAILED',	'This enrolment has been rejected due to Head of Family\'s verification failed. Please re-enrol if you do not have Aadhaar from any other enrolment',	'System',	'System',	Now(),	Now())							
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(88,	'EID_RES_REJECTED_DUE_TO_RESIDENT_VERIFICATION_FAILED',	'This enrolment has been rejected as your verification failed. Please re-enrol if you do not have Aadhaar from any other enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(89,	'EID_RES_REJECTED_DUE_TO_GUARDIAN_LIMIT_FOR_ENROLMENT_EXCEEDED',	'This enrolment has been rejected as guardian\'s limit for enrolment has exceeded. Please re-enrol with documents',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(90,	'EID_RES_REJECTED_DUE_TO_UID_CANCELLED',	'This update request has been rejected as your Aadhaar number has been cancelled. Please re-enrol',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(91,	'EID_RES_REJECTED_DUE_TO_HOF_ENRL_CANCELLED',	'This enrolment has been rejected as head of family\'s enrolment is cancelled. Kindly re-enrol head of family first & then get yourself re-enrolled under him/her OR use any other method for enrolment',	'System',	'System',	Now(),	Now())						
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(92,	'EID_RES_REJECTED_DUE_TO_UID_EID_IS_INVALID',	'This update request has been rejected as Aadhaar Number or Enrolment ID is invalid. Please update again with valid Aadhaar number or Enrolment ID',	'System',	'System',	Now(),	Now())	
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(93,	'EID_RES_REJECTED_DEMO_UPDATE_REQUIRED',	'This update request has been rejected as demographics update is required for your Aadhaar. Please update demographics along with biometrics',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(94,	'EID_RES_REJECTED_DUE_TO_HOF_UID_INACTIVE',	'This enrolment has been rejected as Aadhaar Number of head of family is not active. Activate Head of Family\'s Aadhaar first and re-enrol with active Head of family Aadhaar number OR use any other method for enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(95,	'EID_RES_REJECTED_DUE_TO_HOF_UID_SUSPENDED',	'This enrolment has been rejected as Aadhaar Number of head of family is suspended. Please re-enrol if you do not have Aadhaar from any other enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(96,	'EID_RES_REJECTED_DUE_TO_ORIGINAL_EID_INVALID',	'This update request has been rejected as original EID is not valid. Please update again after Aadhaar generation',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(97,	'EID_RES_REJECTED_DUE_TO_HOF_ENRL_ID_INVALID',	'This update has been rejected as guardian\'s enrolment ID is invalid. Please update again with valid guardian\'s enrolment/Aadhaar Number OR use any other method for update',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(98,	'EID_RES_REJECTED_DUE_TO_HOF_ENRL_IN_PROCESS',	'This enrolment has been rejected as head of family\'s enrolment is in process. Please re-enrol if you do not have Aadhaar, after head of family\'s enrolment gets processed OR use any other method for enrolment',	'System',	'System',	Now(),	Now())						
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(99,	'UID_CANCELLED_DUE_TO_DUPLICATE',	'This Aadhaar number is cancelled due to duplicate.',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(100,	'UID_CANCELLED_DUE_TO_TECHNICAL_ISSUE',	'This Aadhaar is cancelled due to technical issue. Please re-enrol if you do not have Aadhaar from any other enrolment',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(101,	'ERNL_UNDER_PROCESS',	'This enrolment is under process. Please check again after few days',	'System',	'System',	Now(),	Now())
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(102,	'ERNL_UNDER_QUALITY_CHECK',	'This enrolment is under quality check. Please check again after few days',	'System',	'System',	Now(),	Now())						
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(103,	'ENRL_UNDER_MANUAL_BIO_CHECK',	'This enrolment is under manual biometric check. Please check again after few days',	'System',	'System',	Now(),	Now())					
	INSERT INTO `res_statuscode_mst`(`res_statuscode_mst_key`,`res_statuscode_api`,`res_statuscode_msg`,`created_by`,`last_updated_by`,`creation_date`,`last_updated_date`) VALUES	(104,	'UID_SUSPENDED_FOR_DEMOGRAPHIC_ISSUE',	'Your Aadhaar is suspended for demographic issue. Please visit enrolment centre to update your demographic and activate Aadhaar number',	'System',	'System',	Now(),	Now())



"2>> $LOG_FILE
if [ $? -eq 0 ] && [ $error_flag -eq 0 ]
then
echo "Inserted of status API messages in res_statuscode_mstis Successful" >> $LOG_FILE
else
echo "Insertion of status API messages in res_statuscode_mst is failed" >> $LOG_FILE
error_flag=1
exit
fi
echo "Script executed successfully";